// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

/// @dev The viewer script, deployed as an SSTORE2 blob rather than bytecode so
///      later viewers can share it.
library TalismanVertexLitViewerScript {
    string internal constant JS = "var box=document.getElementById('lite-container');"
        "box.style.position=box.style.position||'relative';box.tabIndex=0;"
        "function vS(a,b){return [a[0]-b[0],a[1]-b[1],a[2]-b[2]];}"
        "function vN(a){var L=Math.hypot(a[0],a[1],a[2])||1;return [a[0]/L,a[1]/L,a[2]/L];}"
        "function vC(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}"
        "function vD(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}"
        "function qAA(ax,th){var s=Math.sin(th/2);return [ax[0]*s,ax[1]*s,ax[2]*s,Math.cos(th/2)];}"
        "function qM(a,b){return [a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]];}"
        "function qR(q,v){var x=q[0],y=q[1],z=q[2],w=q[3];var ix=w*v[0]+y*v[2]-z*v[1],iy=w*v[1]+z*v[0]-x*v[2],iz=w*v[2]+x*v[1]-y*v[0],iw=-x*v[0]-y*v[1]-z*v[2];return [ix*w+iw*-x+iy*-z-iz*-y,iy*w+iw*-y+iz*-x-ix*-z,iz*w+iw*-z+ix*-y-iy*-x];}"
        "var f=vN(vS(CT,CP));var up=[0,1,0];var rgt=vN(vC(up,f));var u=vC(f,rgt);"
        "function applyLA(p){var x=p[0]*rgt[0]+p[1]*rgt[1]+p[2]*rgt[2];var y=p[0]*u[0]+p[1]*u[1]+p[2]*u[2];var z=p[0]*f[0]+p[1]*f[1]+p[2]*f[2];return [-x,y,z];}"
        "var focal=1/Math.tan(FOV*Math.PI/180/2);" "var W=512,H=512,S=256;"
        "function proj(p){var z=p[2]<0.1?0.1:p[2];return [W/2+focal*p[0]/z*S,H/2-focal*p[1]/z*S];}"
        "var LDN=LE?vN(LD):[0,0,0];var hasMC=MC[0]!=0||MC[1]!=0||MC[2]!=0;"
        "function shade(p1w,p2w,p3w,baseHex){if(!LE)return baseHex;" "var n=vN(vC(vS(p2w,p1w),vS(p3w,p1w)));"
        "if(hasMC){var ctr=[(p1w[0]+p2w[0]+p3w[0])/3,(p1w[1]+p2w[1]+p3w[1])/3,(p1w[2]+p2w[2]+p3w[2])/3];var to=[ctr[0]-MC[0],ctr[1]-MC[1],ctr[2]-MC[2]];if(vD(n,to)<0){n=[-n[0],-n[1],-n[2]];}}"
        "var d=-vD(n,LDN);"
        "if(d<=0&&hasMC){var ctr2=[(p1w[0]+p2w[0]+p3w[0])/3,(p1w[1]+p2w[1]+p3w[1])/3,(p1w[2]+p2w[2]+p3w[2])/3];var to2=[ctr2[0]-MC[0],ctr2[1]-MC[1],ctr2[2]-MC[2]];if(to2[0]*to2[0]+to2[1]*to2[1]+to2[2]*to2[2]>0){d=-vD(vN(to2),LDN);}}"
        "if(d<0)d=0;" "var br=EMI+REF*(AMB+d*(1-AMB));if(br>1)br=1;if(br<0)br=0;"
        "var nC=parseInt(baseHex.slice(1),16);var r=Math.floor(((nC>>16)&255)*br);var g=Math.floor(((nC>>8)&255)*br);var b=Math.floor((nC&255)*br);"
        "if(r>255)r=255;if(g>255)g=255;if(b>255)b=255;"
        "var hx=((r<<16)|(g<<8)|b).toString(16);while(hx.length<6)hx='0'+hx;return '#'+hx;}"
        "var PULL=0.62,ATM=1.25,SEPS=0.012;"
        "var LP=[CP[0]*PULL,CP[1]*PULL,CP[2]*PULL];var LR=Math.hypot(LP[0],LP[1],LP[2]);"
        "function ipw(x,n){var r=1;while(n>0){if(n&1)r*=x;x*=x;n>>=1;}return r;}"
        "function rgb255(h){var n=parseInt(h.slice(1),16);return [(n>>16)&255,(n>>8)&255,n&255];}"
        "function tone(b,br){return 'rgb('+Math.floor(b[0]*br)+','+Math.floor(b[1]*br)+','+Math.floor(b[2]*br)+')';}"
        "function terms(p1,p2,p3){var n0=vN(vC(vS(p2,p1),vS(p3,p1)));var ps=[p1,p2,p3];var D=[],S=[];"
        "for(var k=0;k<3;k++){var P=ps[k];var Lv=vS(LP,P);var dl=Math.hypot(Lv[0],Lv[1],Lv[2])||1;"
        "var L=[Lv[0]/dl,Lv[1]/dl,Lv[2]/dl];var Vv=vN(vS(CP,P));var n=n0;if(vD(n,Vv)<0)n=[-n[0],-n[1],-n[2]];"
        "var att=Math.min(ATM,LR/dl);var nl=Math.max(0,(vD(n,L)+WRAP)/(1+WRAP))*att;"
        "var br=EMI+GLOW+REF*(AMB+nl*(1-AMB));if(br>1)br=1;if(br<0)br=0;D.push(br);"
        "var H=vN([L[0]+Vv[0],L[1]+Vv[1],L[2]+Vv[2]]);"
        "var sp=ipw(Math.max(0,vD(n,H)),SHIN)*SGAIN*REF+ipw(1-Math.max(0,vD(n,Vv)),RPOW)*RGAIN;"
        "if(sp>1)sp=1;if(sp<0)sp=0;S.push(sp);}return {D:D,S:S};}"
        "function ramp(s,t){var x1=s[0][0],y1=s[0][1],x2=s[1][0],y2=s[1][1],x3=s[2][0],y3=s[2][1];"
        "var det=(x2-x1)*(y3-y1)-(x3-x1)*(y2-y1);if(det===0)return null;"
        "var a=((t[1]-t[0])*(y3-y1)-(t[2]-t[0])*(y2-y1))/det;var b=((x2-x1)*(t[2]-t[0])-(x3-x1)*(t[1]-t[0]))/det;"
        "var g=Math.hypot(a,b);if(g===0)return null;var dx=a/g,dy=b/g;"
        "var lo=0,hi=0,sl=x1*dx+y1*dy,sh2=sl;var ps=[[x1,y1],[x2,y2],[x3,y3]];"
        "for(var k=1;k<3;k++){var sv=ps[k][0]*dx+ps[k][1]*dy;if(sv<sl){sl=sv;lo=k;}if(sv>sh2){sh2=sv;hi=k;}}"
        "if(t[lo]===t[hi])return null;return {x1:dx*sl,y1:dy*sl,x2:dx*sh2,y2:dy*sh2,lo:t[lo],hi:t[hi]};}"
        "var rotQ=[0,0,0,1];var N=V.length/9;var CO=1;" "var stats={fps:0,total:N,front:0,lastT:0,dts:[]};"
        "function buildFrame(){var wV=new Array(N*3);var camV=new Array(N*3);"
        "for(var i=0;i<N;i++){for(var k=0;k<3;k++){var b=i*9+k*3;var v=[V[b],V[b+1],V[b+2]];v=qR(rotQ,v);wV[i*3+k]=v;camV[i*3+k]=applyLA([v[0]-CP[0],v[1]-CP[1],v[2]-CP[2]]);}}"
        "var idx=new Array(N);for(var j=0;j<N;j++)idx[j]=j;"
        "for(var s=1;s<N;s++){var key=idx[s];var d=(camV[key*3][2]+camV[key*3+1][2]+camV[key*3+2][2])/3;var t=s-1;while(t>=0){var dt=(camV[idx[t]*3][2]+camV[idx[t]*3+1][2]+camV[idx[t]*3+2][2])/3;if(dt>=d)break;idx[t+1]=idx[t];t--;}idx[t+1]=key;}"
        "var out=new Array(N);var fc=0;for(var p=0;p<N;p++){var ti=idx[p];var s2d=[proj(camV[ti*3]),proj(camV[ti*3+1]),proj(camV[ti*3+2])];var w2=(s2d[1][0]-s2d[0][0])*(s2d[2][1]-s2d[0][1])-(s2d[1][1]-s2d[0][1])*(s2d[2][0]-s2d[0][0]);if(w2<0)fc++;if(CO&&((CL===1&&w2>=0)||(CL===2&&w2<0))){out[p]=null;continue;}var base=C[M[ti]];if(LIT){var tm=terms(wV[ti*3],wV[ti*3+1],wV[ti*3+2]);var b255=rgb255(base);var av=(tm.D[0]+tm.D[1]+tm.D[2])/3;out[p]={s2d:s2d,D:tm.D,S:tm.S,b:b255,col:tone(b255,av)};}else{out[p]={s2d:s2d,col:shade(wV[ti*3],wV[ti*3+1],wV[ti*3+2],base)};}}stats.front=fc;return out;}"
        "var cv,gl,ctx2d,prog,aPos,aCol,bufP,bufC;var forceMode=null;"
        "function setupBackend(){var oldCv=box.querySelector('canvas');if(oldCv){if(gl){var lx=gl.getExtension&&gl.getExtension('WEBGL_lose_context');if(lx)lx.loseContext();}box.removeChild(oldCv);}"
        "cv=document.createElement('canvas');W=box.clientWidth||512;H=box.clientHeight||512;S=Math.min(W,H)/2;cv.width=W;cv.height=H;box.appendChild(cv);gl=null;ctx2d=null;"
        "if(forceMode!=='2d'){try{gl=cv.getContext('webgl',{antialias:true,alpha:true})||cv.getContext('experimental-webgl',{antialias:true,alpha:true});}catch(e){}}"
        "if(gl){var vsh=gl.createShader(gl.VERTEX_SHADER);gl.shaderSource(vsh,'attribute vec2 a;attribute vec4 c;varying vec4 vc;void main(){vc=c;gl_Position=vec4(a,0.0,1.0);}');gl.compileShader(vsh);"
        "var fsh=gl.createShader(gl.FRAGMENT_SHADER);gl.shaderSource(fsh,'precision mediump float;varying vec4 vc;void main(){gl_FragColor=vec4(vc.rgb*vc.a,vc.a);}');gl.compileShader(fsh);"
        "prog=gl.createProgram();gl.attachShader(prog,vsh);gl.attachShader(prog,fsh);gl.linkProgram(prog);gl.useProgram(prog);"
        "aPos=gl.getAttribLocation(prog,'a');aCol=gl.getAttribLocation(prog,'c');"
        "bufP=gl.createBuffer();bufC=gl.createBuffer();gl.viewport(0,0,W,H);gl.disable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);}"
        "else{ctx2d=cv.getContext('2d');}}" "setupBackend();" "var ov=document.createElement('div');"
        "ov.style.cssText='position:absolute;top:6px;left:6px;background:rgba(0,0,0,0.7);color:#9ef79e;font:11px/1.45 ui-monospace,Menlo,monospace;padding:4px 7px;border-radius:3px;z-index:9;white-space:pre;pointer-events:none;display:'+(DBG?'block':'none')+';';"
        "box.appendChild(ov);"
        "function ovUpdate(){if(ov.style.display==='none')return;var be=gl?'WebGL':'Canvas2D';var fc=forceMode?' [forced]':'';var ft=stats.dts.length?stats.dts[stats.dts.length-1].toFixed(2):'-';ov.textContent='FPS    '+stats.fps.toFixed(1)+'\\nTris   '+stats.total+' (vis '+stats.front+')\\nMode   '+be+fc+'\\nCull   '+(CO?'on':'off')+'\\nLight  '+(LIT?'per-vertex':'flat')+'\\nFrame  '+ft+' ms\\n[D] toggle  [B] backend  [Q] cull  [L] light';}"
        "function hexF(h){var n=parseInt(h.slice(1),16);return [((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255];}"
        "function drawGl(frame){var pa=[],ca=[];"
        "function put(p,r,g,b,al){pa.push(p[0]*2/W-1,1-p[1]*2/H);ca.push(r,g,b,al);}"
        "for(var i=0;i<N;i++){var t=frame[i];if(!t)continue;"
        "if(WF){var rgb=hexF(t.col);var pr=[t.s2d[0],t.s2d[1],t.s2d[1],t.s2d[2],t.s2d[2],t.s2d[0]];"
        "for(var q=0;q<6;q++)put(pr[q],rgb[0],rgb[1],rgb[2],1);continue;}"
        "if(LIT){for(var k=0;k<3;k++)put(t.s2d[k],t.b[0]/255*t.D[k],t.b[1]/255*t.D[k],t.b[2]/255*t.D[k],1);"
        "if(Math.max(t.S[0],t.S[1],t.S[2])>=SEPS){for(var k=0;k<3;k++)put(t.s2d[k],1-TINT*(1-t.b[0]/255),1-TINT*(1-t.b[1]/255),1-TINT*(1-t.b[2]/255),t.S[k]);}}"
        "else{var rgb2=hexF(t.col);for(var k=0;k<3;k++)put(t.s2d[k],rgb2[0],rgb2[1],rgb2[2],1);}}"
        "var w=pa.length/2;pa=new Float32Array(pa);ca=new Float32Array(ca);"
        "gl.clearColor(BG[0],BG[1],BG[2],BGA);gl.clear(gl.COLOR_BUFFER_BIT);"
        "gl.bindBuffer(gl.ARRAY_BUFFER,bufP);gl.bufferData(gl.ARRAY_BUFFER,pa,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(aPos);gl.vertexAttribPointer(aPos,2,gl.FLOAT,false,0,0);"
        "gl.bindBuffer(gl.ARRAY_BUFFER,bufC);gl.bufferData(gl.ARRAY_BUFFER,ca,gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(aCol);gl.vertexAttribPointer(aCol,4,gl.FLOAT,false,0,0);"
        "gl.drawArrays(WF?gl.LINES:gl.TRIANGLES,0,w);}"
        "function path2d(t){ctx2d.beginPath();ctx2d.moveTo(t.s2d[0][0],t.s2d[0][1]);ctx2d.lineTo(t.s2d[1][0],t.s2d[1][1]);ctx2d.lineTo(t.s2d[2][0],t.s2d[2][1]);ctx2d.closePath();}"
        "function draw2d(frame){ctx2d.globalAlpha=1;ctx2d.clearRect(0,0,W,H);"
        "if(BGA>0){ctx2d.fillStyle='rgba('+Math.round(BG[0]*255)+','+Math.round(BG[1]*255)+','+Math.round(BG[2]*255)+','+BGA+')';ctx2d.fillRect(0,0,W,H);}"
        "for(var i=0;i<N;i++){var t=frame[i];if(!t)continue;ctx2d.globalAlpha=1;path2d(t);"
        "if(WF){ctx2d.strokeStyle=t.col;ctx2d.lineWidth=1;ctx2d.stroke();continue;}"
        "if(!LIT){ctx2d.fillStyle=t.col;ctx2d.fill();continue;}" "var dr=ramp(t.s2d,t.D);"
        "if(dr){var gd=ctx2d.createLinearGradient(dr.x1,dr.y1,dr.x2,dr.y2);gd.addColorStop(0,tone(t.b,dr.lo));gd.addColorStop(1,tone(t.b,dr.hi));ctx2d.fillStyle=gd;}"
        "else{ctx2d.fillStyle=t.col;}ctx2d.fill();"
        "var sr=ramp(t.s2d,t.S);var TC='rgba('+Math.round(255-TINT*(255-t.b[0]))+','+Math.round(255-TINT*(255-t.b[1]))+','+Math.round(255-TINT*(255-t.b[2]))+',';"
        "if(sr){if(sr.hi<SEPS)continue;var gs=ctx2d.createLinearGradient(sr.x1,sr.y1,sr.x2,sr.y2);"
        "gs.addColorStop(0,TC+sr.lo.toFixed(3)+')');gs.addColorStop(1,TC+sr.hi.toFixed(3)+')');"
        "ctx2d.fillStyle=gs;path2d(t);ctx2d.fill();}"
        "else{var sa=(t.S[0]+t.S[1]+t.S[2])/3;if(sa<SEPS)continue;ctx2d.globalAlpha=sa;"
        "ctx2d.fillStyle=TC+'1)';path2d(t);ctx2d.fill();}}ctx2d.globalAlpha=1;}"
        "function render(){var t=performance.now();if(stats.lastT){var dt=t-stats.lastT;stats.dts.push(dt);if(stats.dts.length>30)stats.dts.shift();var sum=0;for(var i=0;i<stats.dts.length;i++)sum+=stats.dts[i];stats.fps=stats.dts.length/(sum/1000);}stats.lastT=t;"
        "var frame=buildFrame();if(gl)drawGl(frame);else draw2d(frame);ovUpdate();}render();"
        "if(OC){var down=false,startQ=null,p0=null;"
        "function abV(e){var r=box.getBoundingClientRect();var x=(e.clientX-r.left)/r.width*2-1;var y=(e.clientY-r.top)/r.height*2-1;var d=x*x+y*y;if(d>1){var L=1/Math.sqrt(d);return [x*L,-y*L,0];}return [x,-y,Math.sqrt(1-d)];}"
        "box.addEventListener('mousedown',function(e){down=true;p0=abV(e);startQ=rotQ.slice();box.style.cursor='grabbing';});"
        "box.addEventListener('mousemove',function(e){if(!down)return;var p1=abV(e);var cs=vC(p0,p1);var dt=vD(p0,p1);var aw=[cs[0]*rgt[0]+cs[1]*u[0]-cs[2]*f[0],cs[0]*rgt[1]+cs[1]*u[1]-cs[2]*f[1],cs[0]*rgt[2]+cs[1]*u[2]-cs[2]*f[2]];rotQ=qM([aw[0],aw[1],aw[2],dt],startQ);render();});"
        "box.addEventListener('mouseup',function(){down=false;box.style.cursor='grab';});"
        "box.addEventListener('mouseleave',function(){down=false;});}"
        "if(AR){var aOn=true,aT=null,T0=performance.now();function ar(){if(!aOn)return;requestAnimationFrame(ar);"
        "var k=1;if(SD>0||SE>0){var x=(performance.now()-T0-SD)/(SE||1);k=x<=0?0:x>=1?1:x*x*(3-2*x);}"
        "rotQ=qM(qAA([0,1,0],0.005*k),rotQ);render();}"
        "function arS(){clearTimeout(aT);aT=setTimeout(function(){if(!aOn){aOn=true;ar();}},5000);}"
        "box.addEventListener('mousedown',function(){aOn=false;clearTimeout(aT);});box.addEventListener('mouseup',arS);box.addEventListener('mouseleave',arS);ar();}"
        "window.addEventListener('resize',function(){if(!cv)return;W=box.clientWidth||512;H=box.clientHeight||512;S=Math.min(W,H)/2;cv.width=W;cv.height=H;if(gl)gl.viewport(0,0,W,H);render();});"
        "window.addEventListener('keydown',function(e){if(e.target&&(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA'||e.target.isContentEditable))return;if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='d'||e.key==='D'){ov.style.display=(ov.style.display==='none')?'block':'none';if(ov.style.display==='block')ovUpdate();e.preventDefault();}else if((e.key==='b'||e.key==='B')&&ov.style.display==='block'){forceMode=gl?'2d':null;setupBackend();render();e.preventDefault();}else if((e.key==='q'||e.key==='Q')&&ov.style.display==='block'){CO=CO?0:1;render();e.preventDefault();}else if((e.key==='l'||e.key==='L')&&ov.style.display==='block'){LIT=LIT?0:1;render();e.preventDefault();}});";
}
